# version: '3.8'
services:
  postgres:
    image: postgres:17.4
    container_name: task_postgres
    restart: on-failure
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: taskdb
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - task_network

  redis:
    image: redis:7.4
    container_name: task_redis
    restart: on-failure
    ports:
      - "6379:6379"
    networks:
      - task_network

volumes:
  postgres_data:

networks:
  task_network:
    driver: bridge
